[package]
name = "chengine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.18.1"
eframe = "0.18.0"
crossbeam = "0.8.1"
rand = "0.8.5"
spin = "0.9.3"